2021-11-26 13:53:46,284 ERROR: Exception on / [GET] [in C:\Users\Maestro\Desktop\microblog\venv\lib\site-packages\flask\app.py:1457]
Traceback (most recent call last):
  File "C:\Users\Maestro\Desktop\microblog\venv\lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Maestro\Desktop\microblog\venv\lib\site-packages\flask\app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Maestro\Desktop\microblog\venv\lib\site-packages\flask\app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Maestro\Desktop\microblog\venv\lib\site-packages\flask\app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\Maestro\Desktop\microblog\venv\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\Maestro\Desktop\microblog\app\routes.py", line 41, in index
    return render_template('index.html', title='Home', form=form,
  File "C:\Users\Maestro\Desktop\microblog\venv\lib\site-packages\flask\templating.py", line 148, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "C:\Users\Maestro\Desktop\microblog\venv\lib\site-packages\jinja2\environment.py", line 1068, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "C:\Users\Maestro\Desktop\microblog\venv\lib\site-packages\jinja2\environment.py", line 997, in get_template
    return self._load_template(name, globals)
  File "C:\Users\Maestro\Desktop\microblog\venv\lib\site-packages\jinja2\environment.py", line 958, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "C:\Users\Maestro\Desktop\microblog\venv\lib\site-packages\jinja2\loaders.py", line 137, in load
    code = environment.compile(source, name, filename)
  File "C:\Users\Maestro\Desktop\microblog\venv\lib\site-packages\jinja2\environment.py", line 757, in compile
    self.handle_exception(source=source_hint)
  File "C:\Users\Maestro\Desktop\microblog\venv\lib\site-packages\jinja2\environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\Maestro\Desktop\microblog\app\templates\index.html", line 22, in template
    {% endfor}
jinja2.exceptions.TemplateSyntaxError: unexpected '}'
2021-11-26 13:55:19,883 INFO: Microblog startup [in C:\Users\Maestro\Desktop\microblog\app\__init__.py:46]
2021-11-27 14:30:54,723 INFO: Microblog startup [in C:\Users\Maestro\Desktop\microblog\app\__init__.py:46]
2021-11-27 14:33:02,568 INFO: Microblog startup [in C:\Users\Maestro\Desktop\microblog\app\__init__.py:46]
2021-11-28 07:02:23,299 INFO: Microblog startup [in C:\Users\Maestro\Desktop\microblog\app\__init__.py:49]
2021-11-28 07:05:45,184 INFO: Microblog startup [in C:\Users\Maestro\Desktop\microblog\app\__init__.py:49]
2021-11-28 07:06:07,585 ERROR: Exception on /reset_password_request [POST] [in C:\Users\Maestro\Desktop\microblog\venv\lib\site-packages\flask\app.py:1457]
Traceback (most recent call last):
  File "C:\Users\Maestro\Desktop\microblog\venv\lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Maestro\Desktop\microblog\venv\lib\site-packages\flask\app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Maestro\Desktop\microblog\venv\lib\site-packages\flask\app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Maestro\Desktop\microblog\venv\lib\site-packages\flask\app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\Maestro\Desktop\microblog\app\routes.py", line 166, in reset_password_request
    send_password_reset_email(user)
  File "C:\Users\Maestro\Desktop\microblog\app\email.py", line 14, in send_password_reset_email
    token = user.get_reset_password_token()
  File "C:\Users\Maestro\Desktop\microblog\app\models.py", line 65, in get_reset_password_token
    return jwt.encode(
AttributeError: 'str' object has no attribute 'decode'
2021-11-28 07:08:44,332 INFO: Microblog startup [in C:\Users\Maestro\Desktop\microblog\app\__init__.py:49]
2021-11-28 07:08:54,309 ERROR: Exception on /reset_password_request [POST] [in C:\Users\Maestro\Desktop\microblog\venv\lib\site-packages\flask\app.py:1457]
Traceback (most recent call last):
  File "C:\Users\Maestro\Desktop\microblog\venv\lib\site-packages\flask_mail.py", line 492, in send
    message.send(connection)
  File "C:\Users\Maestro\Desktop\microblog\venv\lib\site-packages\flask_mail.py", line 427, in send
    connection.send(self)
  File "C:\Users\Maestro\Desktop\microblog\venv\lib\site-packages\flask_mail.py", line 188, in send
    self.host.sendmail(sanitize_address(envelope_from or message.sender),
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2544.0_x64__qbz5n2kfra8p0\lib\smtplib.py", line 872, in sendmail
    self.ehlo_or_helo_if_needed()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2544.0_x64__qbz5n2kfra8p0\lib\smtplib.py", line 611, in ehlo_or_helo_if_needed
    if not (200 <= self.ehlo()[0] <= 299):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2544.0_x64__qbz5n2kfra8p0\lib\smtplib.py", line 451, in ehlo
    self.putcmd(self.ehlo_msg, name or self.local_hostname)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2544.0_x64__qbz5n2kfra8p0\lib\smtplib.py", line 378, in putcmd
    self.send(f'{s}{CRLF}')
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2544.0_x64__qbz5n2kfra8p0\lib\smtplib.py", line 365, in send
    raise SMTPServerDisconnected('please run connect() first')
smtplib.SMTPServerDisconnected: please run connect() first

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Maestro\Desktop\microblog\venv\lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Maestro\Desktop\microblog\venv\lib\site-packages\flask\app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Maestro\Desktop\microblog\venv\lib\site-packages\flask\app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Maestro\Desktop\microblog\venv\lib\site-packages\flask\app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\Maestro\Desktop\microblog\app\routes.py", line 166, in reset_password_request
    send_password_reset_email(user)
  File "C:\Users\Maestro\Desktop\microblog\app\email.py", line 15, in send_password_reset_email
    send_email('[Microblog] Reset Your Password',
  File "C:\Users\Maestro\Desktop\microblog\app\email.py", line 10, in send_email
    mail.send(msg)
  File "C:\Users\Maestro\Desktop\microblog\venv\lib\site-packages\flask_mail.py", line 492, in send
    message.send(connection)
  File "C:\Users\Maestro\Desktop\microblog\venv\lib\site-packages\flask_mail.py", line 152, in __exit__
    self.host.quit()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2544.0_x64__qbz5n2kfra8p0\lib\smtplib.py", line 1004, in quit
    res = self.docmd("quit")
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2544.0_x64__qbz5n2kfra8p0\lib\smtplib.py", line 431, in docmd
    self.putcmd(cmd, args)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2544.0_x64__qbz5n2kfra8p0\lib\smtplib.py", line 378, in putcmd
    self.send(f'{s}{CRLF}')
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2544.0_x64__qbz5n2kfra8p0\lib\smtplib.py", line 365, in send
    raise SMTPServerDisconnected('please run connect() first')
smtplib.SMTPServerDisconnected: please run connect() first
2021-11-28 11:51:10,070 INFO: Microblog startup [in C:\Users\Maestro\Desktop\microblog\app\__init__.py:49]
2021-11-28 19:55:57,427 INFO: Microblog startup [in C:\Users\Maestro\Desktop\microblog\app\__init__.py:51]
2021-11-29 07:22:56,859 INFO: Microblog startup [in C:\Users\Maestro\Desktop\microblog\app\__init__.py:52]
2021-11-29 07:44:57,967 INFO: Microblog startup [in C:\Users\Maestro\Desktop\microblog\app\__init__.py:52]
2021-11-29 07:46:21,118 INFO: Microblog startup [in C:\Users\Maestro\Desktop\microblog\app\__init__.py:52]
2021-11-29 07:55:46,882 INFO: Microblog startup [in C:\Users\Maestro\Desktop\microblog\app\__init__.py:52]
2021-11-29 08:18:25,669 INFO: Microblog startup [in C:\Users\Maestro\Desktop\microblog\app\__init__.py:52]
